CREATE DATABASE IF NOT EXISTS blog;

CREATE USER 'yasmin' IDENTIFIED BY 'password';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `blog`.* TO 'yasmin';

FLUSH PRIVILEGES;