version: '3.8'
services:
  database:
    image: library/postgres:13.2
    restart: always
    container_name: database_blog
    volumes:
      - data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=yasmin
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PASSWORD=yasmin
    ports:
      - "5432:5432"
volumes:
  data: